PERGUNTAS_DREXUS = {
    "IF": [
        "1 - A missão crítica da unidade está claramente definida e operacionalizada?",
        "2 - Os processos essenciais operam sob contingência mínima com autonomia funcional?",
        "3 - A cadeia de decisão se mantém funcional durante eventos extremos?",
        "4 - As equipes conhecem e priorizam a missão crítica sob pressão?",
        "5 - Há redundância mínima viável para manter a integridade operacional?",
        "6 - Os sistemas de controle de qualidade funcionam mesmo em contextos adversos?",
        "7 - A liderança consegue reorganizar recursos rapidamente sem comprometer a missão?",
        "8 - Existe teste periódico da resiliência dos processos críticos?",
        "9 - Há indicadores de missão crítica com resposta em tempo real?",
        "10 - A integridade dos processos é percebida e valorizada pela cultura da organização?",
    ],
    "Cm": [
        "11 - A estrutura permite isolamento funcional de áreas ou processos sob falha?",
        "12 - Os processos críticos são escaláveis e recombináveis?",
        "13 - A organização utiliza unidades operacionais redundantes e distribuídas?",
        "14 - Há protocolos formais para redistribuir operações sob estresse?",
        "15 - A cultura organizacional aceita e estimula a recombinação de funções?",
        "16 - Existe padronização flexível entre unidades (ex.: protocolos intercambiáveis)?",
        "17 - A TI suporta transição modular sem queda de performance?",
        "18 - Há plano de emergência baseado em módulos substituíveis?",
        "19 - O sistema de governança comporta múltiplas formas de operação simultânea?",
        "20 - A organização usa testes A/B ou pilotos modulares para validar mudanças?",
    ],
    "Et": [
        "21 - A organização registra sistematicamente lições aprendidas após eventos críticos?",
        "22 - Há comitês ou espaços formais para análise pós-crise?",
        "23 - O aprendizado gerado em crises anteriores foi implementado em novos processos?",
        "24 - Existe cultura de melhoria contínua reativa a eventos imprevisíveis?",
        "25 - As equipes compartilham aprendizado tático em tempo real?",
        "26 - Os relatórios de lições aprendidas geram mudanças de prática?",
        "27 - Há ajustes institucionais após falhas (regulamentos, metas, recursos)?",
        "28 - Existe rastreabilidade entre evento-crise e mudança posterior?",
        "29 - A liderança acompanha pessoalmente o ciclo de evolução pós-crise?",
        "30 - A organização possui histórico documentado de transformações oriundas de eventos críticos?",
    ],
    "DREq": [
        "31 - Foram tomadas DREs documentadas nos últimos 12 meses?",
        "32 - Existem rituais ou fóruns estratégicos com foco em DREs?",
        "33 - A cultura reconhece e valoriza decisões que resolvem e evoluem simultaneamente?",
        "34 - As DREs influenciaram mais de uma área ou nível da organização?",
        "35 - Há líderes formalmente treinados para identificar e conduzir DREs?",
        "36 - DREs fazem parte de indicadores de desempenho institucional?",
        "37 - Existe orçamento ou incentivo dedicado à execução de DREs?",
        "38 - O conselho ou alta liderança aprova DREs estruturais de médio/longo prazo?",
        "39 - Há integração entre DREs e processos de inovação?",
        "40 - Existe governança clara para rastrear o ciclo de vida de uma DRE?",
    ],
    "Lc": [
        "41 - A liderança consegue decidir com rapidez mesmo sem todos os dados disponíveis?",
        "42 - A organização já tomou decisões importantes com base em cenários e não apenas em fatos lineares?",
        "43 - Há incentivo à leitura de sinais fracos e tendências antes que se tornem óbvias?",
        "44 - A empresa incorpora contradições e ambivalências em sua análise de contexto?",
        "45 - Existe uso de frameworks de complexidade para suporte à decisão (ex.: Cynefin, ICE³-R)?",
        "46 - A lógica utilizada nas decisões é ajustada à situação e não padronizada de forma cega?",
        "47 - São usados mapas mentais, sistemas ou heurísticas visuais para decisões ambíguas?",
        "48 - A organização revisa o contexto periodicamente durante execução de planos estratégicos?",
        "49 - A comunicação interna reconhece zonas de dúvida sem prejuízo à ação?",
        "50 - Existe formação específica para decisões em ambientes de incerteza?",
    ],
    "Im": [
        "51 - As DREs recentes impactaram mais de um setor ou unidade da organização?",
        "52 - As decisões provocaram mudanças permanentes em políticas, cultura ou estrutura?",
        "53 - Houve aprendizado organizacional replicado após a DRE?",
        "54 - As decisões geraram novos modelos de negócio, fluxos ou produtos?",
        "55 - Os efeitos positivos da DRE se estenderam para stakeholders externos (clientes, parceiros, comunidade)?",
        "56 - Existe mensuração formal do impacto estrutural das DREs?",
        "57 - A decisão provocou realinhamento de governança, processos ou propósito?",
        "58 - Os aprendizados foram transformados em novos sistemas (tecnologia, cultura, protocolos)?",
        "59 - Há difusão do impacto da DRE para subsidiárias ou outras regiões?",
        "60 - A decisão motivou movimentos similares em outras organizações ou redes?",
    ],
    "Pv": [
        "61 - As decisões estratégicas alinham-se claramente ao propósito institucional atual?",
        "62 - O propósito da organização é revisitado e atualizado com base em eventos e aprendizados?",
        "63 - As equipes compreendem o propósito e sabem como se conectar a ele no dia a dia?",
        "64 - Existe espaço para evolução orgânica do propósito institucional (não é estático)?",
        "65 - O propósito orienta investimentos, inovação e posicionamento de longo prazo?",
        "66 - As métricas estratégicas estão alinhadas ao propósito (ex.: não apenas ROI, mas impacto regenerativo)?",
        "67 - A liderança toma decisões difíceis com base em coerência com o propósito?",
        "68 - Há canal formal para revisão participativa do propósito institucional?",
        "69 - Os discursos institucionais são coerentes com a prática?",
        "70 - O propósito é usado como referência explícita para decisões regenerativas?",
    ],
}
