PERGUNTAS_TABELAS = {
    'AQI_BIA': {
        'processo': 'Qual é o processo analisado?',
        'rto': 'Tempo de Recuperação Objetivo (RTO em horas)',
        'mtpd': 'Período Máximo de Interrupção Tolerável (MTPD em horas)',
        'impacto_financeiro_1h': 'Qual o impacto financeiro após 1 hora?',
        'impacto_financeiro_4h': 'Qual o impacto financeiro após 4 hora?',
        'impacto_financeiro_8h': 'Qual o impacto financeiro após 8 hora?',
        'impacto_financeiro_24h': 'Qual o impacto financeiro após 24 hora?',
        'impacto_financeiro_48h': 'Qual o impacto financeiro após 48 hora?',
        'impacto_financeiro_REAL': 'Qual o impacto financeiro Real?',
        'impacto_img_rep_1h': 'Qual o impacto da imagem e reputação após 1 hora?',
        'impacto_img_rep_4h': 'Qual o impacto da imagem e reputação após 4 hora?',
        'impacto_img_rep_8h': 'Qual o impacto da imagem e reputação após 8 hora?',
        'impacto_img_rep_24h': 'Qual o impacto da imagem e reputação após 24 hora?',
        'impacto_img_rep_48h': 'Qual o impacto da imagem e reputação após 48 hora?',
        'impacto_img_rep_REAL': 'Qual o impacto da imagem e reputação Real?',
        'impacto_operacional_1h': 'Qual o impacto operacional após 1 hora?',
        'impacto_operacional_4h': 'Qual o impacto operacional após 4 hora?',
        'impacto_operacional_8h': 'Qual o impacto operacional após 8 hora?',
        'impacto_operacional_24h': 'Qual o impacto operacional após 24 hora?',
        'impacto_operacional_48h': 'Qual o impacto operacional após 48 hora?',
        'impacto_operacional_REAL': 'Qual o impacto operacional Real?',
        'impacto_legal_1h': 'Qual o impacto legal e compliance após 1 hora?',
        'impacto_legal_4h': 'Qual o impacto legal e compliance após 4 hora?',
        'impacto_legal_8h': 'Qual o impacto legal e compliance após 8 hora?',
        'impacto_legal_24h': 'Qual o impacto legal e compliance após 24 hora?',
        'impacto_legal_48h': 'Qual o impacto legal e compliance após 48 hora?',
        'impacto_legal_REAL': 'Qual o impacto legal e compliance Real?',
        'impacto_ambiental_1h': 'Qual o impacto ambiental após 1 hora?',
        'impacto_ambiental_4h': 'Qual o impacto ambiental após 4 hora?',
        'impacto_ambiental_8h': 'Qual o impacto ambiental após 8 hora?',
        'impacto_ambiental_24h': 'Qual o impacto ambiental após 24 hora?',
        'impacto_ambiental_48h': 'Qual o impacto ambiental após 48 hora?',
        'impacto_ambiental_REAL': 'Qual o impacto ambiental Real?',
        'base': 'Qual a base?'
    },

    'CQP_BIA': {
        'classificacao_impacto': 'Qual a Classificação do Impacto?',
        'probabilidade': 'Qual a Probabilidade de ocorrência?',
        'total_criticidade': 'Qual o Total de Criticidade?',
        'processos': 'Quais são os Processos Envolvidos?',
        'rto': 'Qual o RTO?',
        'area': 'Qual a Área Responsável?',
    },

    'CADASTRO_BIA': {
        'processos': 'Qual o Processo Principal?',
        'area': 'Área do Processo',
        'nicho': 'Nicho de Atuação',
        'responsavel': 'Quem é o Responsável pelo Processo?',
        'cenario': 'Qual o Cenário de Interrupção?',
        'probabilidade': 'Qual a Probabilidade de Ocorrência?',
    },

    'SISTEMAS_TI': {
        'subprocessos': 'Subprocesso Associado',
        'aplicacoes_sistemas': 'Aplicação / Sistema',
        'url': 'URL de Acesso',
        'alternativa_manual': 'Existe Alternativa Manual?',
        'impacto_aplicacoes_30min': 'Qual o impacto das aplicações e sistemas após 30 minútos?',
        'impacto_aplicacoes_1h': 'Qual o impacto das aplicações e sistemas após 1 hora?',
        'impacto_aplicacoes_2h': 'Qual o impacto das aplicações e sistemas após 2 hora?',
        'impacto_aplicacoes_6h': 'Qual o impacto das aplicações e sistemas após 6 hora?',
        'impacto_aplicacoes_8h': 'Qual o impacto das aplicações e sistemas após 8 hora?',
        'impacto_aplicacoes_12h': 'Qual o impacto das aplicações e sistemas após 12 horas?',
        'impacto_aplicacoes_24h': 'Qual o impacto das aplicações e sistemas após 24 hora?',
        'impacto_aplicacoes_mais_24h': 'Qual o impacto das aplicações e sistemas após mais de 24 horas?',
        'rto': 'Qual o RTO?',
        'rpo': 'Qual o RPO?',
        'observacao': "Observações:"    
    },

    'PROBABILIDADE': {
        'processos': 'Qual o Processo Principal?',
        'nicho': 'Nicho de Atuação',
    },

    'PARAMETRIZACAO': {
        'valor_exposicao_1': 'Qual o valor do impacto financeiro por exposição para o nível 1?',
        'img_rep_midias_1': 'Qual o valor do impacto na imagem e reputação pelas mídias para o nível 1?',
        'img_rep_stakeholders_1': 'Qual o valor do impacto na imagem e reputação pelos Stakeholders para o nível 1?',
        'legal_penalidade_1': 'Qual o valor do impacto legal e compliance por penalidade para o nível 1?',
        'legal_contrato_1': 'Qual o valor do impacto legal e compliance por contrato para o nível 1?',
        'amb_1': 'Qual o valor do impacto ambiental para o nível 1?',
        'social_1': 'Qual o valor do impacto social para o nível 1?',
        'estrategia_1': 'Qual o valor do impacto na Estratégica e Governança para o nível 1?',
        'valor_exposicao_2': 'Qual o valor do impacto financeiro por exposição para o nível 2?',
        'img_rep_midias_2': 'Qual o valor do impacto na imagem e reputação pelas mídias para o nível 2?',
        'img_rep_stakeholders_2': 'Qual o valor do impacto na imagem e reputação pelos Stakeholders para o nível 2?',
        'legal_penalidade_2': 'Qual o valor do impacto legal e compliance por penalidade para o nível 2?',
        'legal_contrato_2': 'Qual o valor do impacto legal e compliance por contrato para o nível 2?',
        'amb_2': 'Qual o valor do impacto ambiental para o nível 2?',
        'social_2': 'Qual o valor do impacto social para o nível 2?',
        'estrategia_2': 'Qual o valor do impacto na Estratégica e Governança para o nível 2?',
        'valor_exposicao_3': 'Qual o valor do impacto financeiro por exposição para o nível 3?',
        'img_rep_midias_3': 'Qual o valor do impacto na imagem e reputação pelas mídias para o nível 3?',
        'img_rep_stakeholders_3': 'Qual o valor do impacto na imagem e reputação pelos Stakeholders para o nível 3?',
        'legal_penalidade_3': 'Qual o valor do impacto legal e compliance por penalidade para o nível 3?',
        'legal_contrato_3': 'Qual o valor do impacto legal e compliance por contrato para o nível 3?',
        'amb_3': 'Qual o valor do impacto ambiental para o nível 3?',
        'social_3': 'Qual o valor do impacto social para o nível 3?',
        'estrategia_3': 'Qual o valor do impacto na Estratégica e Governança para o nível 3?',
        'valor_exposicao_4': 'Qual o valor do impacto financeiro por exposição para o nível 4?',
        'img_rep_midias_4': 'Qual o valor do impacto na imagem e reputação pelas mídias para o nível 4?',
        'img_rep_stakeholders_4': 'Qual o valor do impacto na imagem e reputação pelos Stakeholders para o nível 4?',
        'legal_penalidade_4': 'Qual o valor do impacto legal e compliance por penalidade para o nível 4?',
        'legal_contrato_4': 'Qual o valor do impacto legal e compliance por contrato para o nível 4?',
        'amb_4': 'Qual o valor do impacto ambiental para o nível 4?',
        'social_4': 'Qual o valor do impacto social para o nível 4?',
        'estrategia_4': 'Qual o valor do impacto na Estratégica e Governança para o nível 4?',
        'valor_exposicao_5': 'Qual o valor do impacto financeiro por exposição para o nível 5?',
        'img_rep_midias_5': 'Qual o valor do impacto na imagem e reputação pelas mídias para o nível 5?',
        'img_rep_stakeholders_5': 'Qual o valor do impacto na imagem e reputação pelos Stakeholders para o nível 5?',
        'legal_penalidade_5': 'Qual o valor do impacto legal e compliance por penalidade para o nível 5?',
        'legal_contrato_5': 'Qual o valor do impacto legal e compliance por contrato para o nível 5?',
        'amb_5': 'Qual o valor do impacto ambiental para o nível 5?',
        'social_5': 'Qual o valor do impacto social para o nível 5?',
        'estrategia_5': 'Qual o valor do impacto na Estratégica e Governança para o nível 5?',
    }    
}