# Generated by Django 5.2.3 on 2025-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drexus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('diagnostico', models.CharField(default='', max_length=100)),
                ('diagnostico_maturidade', models.CharField(default='', max_length=100)),
                ('diagnostico_cognitiva', models.CharField(default='', max_length=100)),
                ('diagnostico_estrategica', models.CharField(default='', max_length=100)),
                ('diagnostico_operacional', models.CharField(default='', max_length=100)),
                ('diagnostico_cultural', models.CharField(default='', max_length=100)),
                ('IF', models.FloatField(default=0)),
                ('Cm', models.FloatField(default=0)),
                ('Et', models.FloatField(default=0)),
                ('DREq', models.FloatField(default=0)),
                ('Lc', models.FloatField(default=0)),
                ('Im', models.FloatField(default=0)),
                ('Pv', models.FloatField(default=0)),
                ('maturidade_cognitiva', models.FloatField(default=0)),
                ('maturidade_estrategica', models.FloatField(default=0)),
                ('maturidade_operacional', models.FloatField(default=0)),
                ('maturidade_cultural', models.FloatField(default=0)),
                ('IF_notas', models.JSONField(default=list)),
                ('Cm_notas', models.JSONField(default=list)),
                ('Et_notas', models.JSONField(default=list)),
                ('DREq_notas', models.JSONField(default=list)),
                ('Lc_notas', models.JSONField(default=list)),
                ('Im_notas', models.JSONField(default=list)),
                ('Pv_notas', models.JSONField(default=list)),
                ('nota_final', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='andamento', max_length=20)),
            ],
        ),
    ]
