# Generated by Django 5.2.1 on 2025-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_remove_projeto_slug_alter_projeto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drexus',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('IF', models.FloatField(default=0)),
                ('Cm', models.FloatField(default=0)),
                ('Et', models.FloatField(default=0)),
                ('DREq', models.FloatField(default=0)),
                ('Lc', models.FloatField(default=0)),
                ('Im', models.FloatField(default=0)),
                ('Pv', models.FloatField(default=0)),
                ('IF_notas', models.JSONField(default=list)),
                ('Cm_notas', models.JSONField(default=list)),
                ('Et_notas', models.JSONField(default=list)),
                ('DREq_notas', models.JSONField(default=list)),
                ('Lc_notas', models.JSONField(default=list)),
                ('Im_notas', models.JSONField(default=list)),
                ('Pv_notas', models.JSONField(default=list)),
                ('nota_final', models.FloatField(default=0)),
            ],
        ),
    ]
