# Generated by Django 5.2.2 on 2025-08-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_parametrizacaobia_operacional_nivel_1_impactos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_operacao', models.CharField(max_length=255, verbose_name='Qual o nome da operação a ser parametrizada?')),
                ('valor_nivel_1', models.CharField(max_length=255, verbose_name='Qual o valor do operacional para o nível 1?')),
                ('valor_nivel_2', models.CharField(max_length=255, verbose_name='Qual o valor do operacional para o nível 2?')),
                ('valor_nivel_3', models.CharField(max_length=255, verbose_name='Qual o valor do operacional para o nível 3?')),
                ('valor_nivel_4', models.CharField(max_length=255, verbose_name='Qual o valor do operacional para o nível 4?')),
                ('valor_nivel_5', models.CharField(max_length=255, verbose_name='Qual o valor do operacional para o nível 5?')),
                ('parametrizacao_bia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_operacionais', to='projetos.parametrizacaobia', verbose_name='Parametrização BIA Associada')),
            ],
        ),
    ]
