# Generated by Django 5.2.1 on 2025-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_drexus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='andamento', max_length=20),
        ),
    ]
