# Generated by Django 5.2.2 on 2025-08-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_operacaooperacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrizacaobia',
            name='operacional_nivel_1_impactos',
        ),
        migrations.RemoveField(
            model_name='parametrizacaobia',
            name='operacional_nivel_2_impactos',
        ),
        migrations.RemoveField(
            model_name='parametrizacaobia',
            name='operacional_nivel_3_impactos',
        ),
        migrations.RemoveField(
            model_name='parametrizacaobia',
            name='operacional_nivel_4_impactos',
        ),
        migrations.RemoveField(
            model_name='parametrizacaobia',
            name='operacional_nivel_5_impactos',
        ),
    ]
