# Generated by Django 5.2.1 on 2025-06-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drexus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
