# Generated by Django 5.2.2 on 2025-08-04 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_remove_parametrizacaobia_operacional_nivel_1_impactos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaBia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Qual é a Área analisada?')),
                ('macroprocesso', models.CharField(max_length=255, verbose_name='Qual é o Macroprocesso analisado?')),
                ('processo', models.CharField(max_length=255, verbose_name='Qual é o Processo analisado?')),
                ('subprocesso', models.CharField(max_length=255, verbose_name='Qual é o Subprocesso analisado?')),
                ('descricao', models.TextField(verbose_name='Descreva resumidamente a atividade final!')),
                ('aspectos_regulatorios', models.TextField(blank=True, null=True, verbose_name='Aspectos Regulatórios')),
                ('aspectos_contratuais', models.TextField(blank=True, null=True, verbose_name='Aspectos Contratuais')),
                ('entradas_interface', models.TextField(blank=True, null=True, verbose_name='Entradas (Interfaces)')),
                ('saidas_interface', models.TextField(blank=True, null=True, verbose_name='Saídas (Interfaces)')),
                ('volumetrias_interface', models.TextField(blank=True, null=True, verbose_name='Volumetrias (Interfaces)')),
                ('volumetrias_criticas', models.TextField(blank=True, null=True, verbose_name='Volumetrias Críticas')),
                ('slas_volumetrias', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLAs (Volumetrias) em horas')),
                ('rh', models.TextField(blank=True, null=True, verbose_name='Recursos Humanos')),
                ('regime_operacao_equipe', models.TextField(blank=True, null=True, verbose_name='Regime de Operação da Equipe')),
                ('equipe_critica', models.TextField(blank=True, null=True, verbose_name='Equipe Crítica')),
                ('contingencias_rh', models.TextField(blank=True, null=True, verbose_name='Contingências (RH)')),
                ('slas_rh', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLAs (RH) em horas')),
                ('fornecedores', models.TextField(blank=True, null=True, verbose_name='Fornecedores')),
                ('lead_time_insumos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead Time (Insumos)')),
                ('contingencias_insumos', models.TextField(blank=True, null=True, verbose_name='Contingências (Insumos)')),
                ('slas_insumos', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLAs (Insumos) em horas')),
                ('sistemas_ti_ta', models.TextField(blank=True, null=True, verbose_name='Sistemas TI TA')),
                ('sistemas_criticos_usuario', models.TextField(blank=True, null=True, verbose_name='Sistemas Críticos (Usuário)')),
                ('contingencias_sistemas', models.TextField(blank=True, null=True, verbose_name='Contingências (Sistemas)')),
                ('slas_sistemas', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLAs (Sistemas) em horas')),
                ('equipamentos', models.TextField(blank=True, null=True, verbose_name='Equipamentos Utilizados')),
                ('equipamentos_criticos', models.TextField(blank=True, null=True, verbose_name='Equipamentos Críticos')),
                ('slas_equipamentos', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLAs (Equipamentos) em horas')),
                ('pontos_criticidade', models.TextField(blank=True, null=True, verbose_name='Pontos de Criticidade')),
                ('pior_cenario', models.TextField(blank=True, null=True, verbose_name='Pior Cenário')),
                ('mtpd_horas', models.CharField(blank=True, max_length=255, null=True, verbose_name='MTPD em horas')),
                ('descricao_motivo_mtpd', models.TextField(blank=True, null=True, verbose_name='Descrição do Motivo MTPD')),
                ('rto_horas', models.CharField(blank=True, max_length=255, null=True, verbose_name='RTO em horas')),
                ('rpo_horas', models.CharField(blank=True, max_length=255, null=True, verbose_name='RPO em horas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_bia', to='projetos.projeto')),
            ],
        ),
    ]
