# Generated by Django 5.2.1 on 2025-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_drexus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drexus',
            name='maturidade_cognitiva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drexus',
            name='maturidade_cultural',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drexus',
            name='maturidade_estrategica',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drexus',
            name='maturidade_operacional',
            field=models.FloatField(default=0),
        ),
    ]
