# Generated by Django 5.2.2 on 2025-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_entrevistabia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrobia',
            name='probabilidade',
            field=models.CharField(choices=[('Remota', 'Remota'), ('Possível', 'Possível'), ('Provável', 'Provável'), ('Muito Provável', 'Muito Provável')], default='Remota', max_length=20),
        ),
    ]
