# Generated by Django 5.2.1 on 2025-06-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_drexus_maturidade_cognitiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drexus',
            name='diagnostico',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drexus',
            name='diagnostico_cognitiva',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drexus',
            name='diagnostico_cultural',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drexus',
            name='diagnostico_estrategica',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drexus',
            name='diagnostico_maturidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drexus',
            name='diagnostico_operacional',
            field=models.CharField(default='', max_length=100),
        ),
    ]
