# Generated by Django 5.2.2 on 2025-08-11 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_alter_cadastrobia_probabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='drexus',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('movido', 'Movido para BIA')], default='ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='analise_drexus_original',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.drexus'),
        ),
    ]
